CONFIG_ZMK_SLEEP=y

# nice!view screen from mctechnology17/zmk-nice-oled (shield nice_epaper).
# Widget options: https://github.com/mctechnology17/zmk-nice-oled#configuration
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Milliseconds of inactivity before entering idle state	
# CONFIG_ZMK_IDLE_TIMEOUT=600000
# Milliseconds of inactivity before entering deep sleep
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=180000
# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y
