CONFIG_ZMK_SLEEP=y

# nice!view status screen (stock nice_view shield).
CONFIG_ZMK_DISPLAY=y

# Milliseconds of inactivity before entering idle state	
# CONFIG_ZMK_IDLE_TIMEOUT=600000
# Milliseconds of inactivity before entering deep sleep
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=180000
# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y
